import pyautogui
import time

print("Quantos pedidos precisam de declaracao?")
pedidos = input()
contador = 0

pyautogui.keyDown("alt")
pyautogui.press("tab")
pyautogui.keyUp("alt")
time.sleep(0.5)
pyautogui.press("tab")
pyautogui.hotkey("ctrl","c")
pyautogui.keyDown("shift")
pyautogui.press("tab")
pyautogui.keyUp("shift")
time.sleep(0.5)
pyautogui.keyDown("alt")
pyautogui.press("tab")
pyautogui.press("tab")
pyautogui.keyUp("alt")
time.sleep(0.5)
pyautogui.hotkey("ctrl","t")
pyautogui.hotkey("ctrl","v")
pyautogui.keyDown("alt")
pyautogui.press("tab")
pyautogui.keyUp("alt")
pyautogui.hotkey("ctrl","c")
pyautogui.keyDown("alt")
pyautogui.press("tab")
pyautogui.keyUp("alt")
pyautogui.hotkey("ctrl","v")
pyautogui.press("enter")
time.sleep(25)
pyautogui.press("enter")
time.sleep(10)
pyautogui.keyDown("alt")
pyautogui.press("tab")
pyautogui.keyUp("alt")
pyautogui.press("down")

while contador != pedidos:
	pyautogui.press("tab")
	pyautogui.hotkey("ctrl","c")
	pyautogui.keyDown("shift")
	pyautogui.press("tab")
	pyautogui.keyUp("shift")

	pyautogui.keyDown("alt")
	pyautogui.press("tab")
	pyautogui.keyUp("alt")
	pyautogui.hotkey("ctrl","t")
	pyautogui.hotkey("ctrl","v")

	pyautogui.keyDown("alt")
	pyautogui.press("tab")
	pyautogui.keyUp("alt")
	pyautogui.hotkey("ctrl","c")
	pyautogui.keyDown("alt")
	pyautogui.press("tab")
	pyautogui.keyUp("alt")
	pyautogui.hotkey("ctrl","v")
	
	time.sleep(35)
	pyautogui.sleep(enter)
	time.sleep(15)
	pyautogui.sleep(enter)
	pyautogui.keyDown("alt")
	pyautogui.press("tab")
	pyautogui.keyUp("alt")
	pyautogui.press("down")
	contador = contador + 1